# Fundamental concepts of tensors using TensorFlow

* Introduction to tensors
* Getting information about tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function (on this way we will speed up our regular Python functions)
* Using GPUs with TensorFlow (or TPUs - fast numberical computing)

# Introduction to tensors

In [1]:
import tensorflow as tf

print(tf.__version__)

2.15.0


# Tensors



In [2]:
# Creating tensors with tf.contant()
# Scaler is a single number
scaler =tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Checking the number of dimensions of a tensor (ndim stands for the number of dimensions)
scaler.ndim


0

In [4]:
# Creating a vector
vector=tf.constant([10,10])
vector



<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
# Vector is a number with direction
vector.ndim

1

In [6]:
# Create a matrix (has more then 1 dimension)
# Two dimensional array of numbers
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [9]:
# Specifying the data type (dtype), by default int32 (32 bit precision)
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
# Creating a tensor
# Tensor is n-dimensional array of numbers
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [14]:
# Dimension of tensor
tensor.ndim

3