# Fundamental concepts of tensors using TensorFlow

* Introduction to tensors
* Getting information about tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function (on this way we will speed up our regular Python functions)
* Using GPUs with TensorFlow (or TPUs - fast numberical computing)

# Introduction to tensors

In [2]:
import tensorflow as tf

print(tf.__version__)

2.15.0


# Tensors



## Creating tensors with tf.contant()

In [3]:
# Creating tensors with tf.contant()
# Scaler is a single number
scaler =tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Checking the number of dimensions of a tensor (ndim stands for the number of dimensions)
scaler.ndim


0

In [5]:
# Creating a vector
vector=tf.constant([10,10])
vector



<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimension of our vector
# Vector is a number with direction
vector.ndim

1

In [7]:
# Create a matrix (has more then 1 dimension)
# Two dimensional array of numbers
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Specifying the data type (dtype), by default int32 (32 bit precision)
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# Creating a tensor
# Tensor is n-dimensional array of numbers
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [11]:
# Dimension of tensor
tensor.ndim

3

## Creating tensors with tf.Variable

In [12]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Changing values inside the tensor that's creating in a way with using Variable
# changeable_tensor[0]=20 -> on this way we can not change the value of tensor,
# instead we can try to do it with next line
changeable_tensor[0].assign(20)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([20,  7], dtype=int32)>

In [14]:
# Changing the value inside the tensor that's created using a constant

# unchangeable_tensor[0]=60 can not assing a value on this way
# unchangeable_tensor[0].assing(60) can not assing a value because it's not defined for tensor that's created on a way using contant

## Creating random tensors


In [15]:
# Random tensors are tensors of some abitrary size which contain random numbers
random_1 = tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2)) #normal distribution
random_2

# Are they equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

- Shuffle a tensor (this might be good for learning on our model).
- E.g. if we have 10k images of cats and after that 5k images of dogs, our model may not learn well because he will not know how to recognize the dogs, because we learned a model only on cats e.g. 
- This is valuable when we want to shuffle our data so the inehrit order doesn't effect learning


In [24]:
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
# Shuffling the tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

### Creating tensors on different ways

In [28]:
# Creating a tensor of all ones
tf.ones([10,7])

#Creating the tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turning NumPy arrays to tensors

- Different between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [34]:
# Can also turn NumPy arrays to tensors
import numpy as np
numpy_A =np.arange(1,25,dtype=np.int32)

A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>